services:
  docs:
    image: lego_deck_local_docs
    container_name: lego_deck_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./lego_deck:/app/lego_deck:z
    ports:
      - '9000:9000'
    command: /start-docs
